chore: Moar keys (#22)
* chore: Moar keys
* fix: clicky clicky links work now
* fix: colours like  boss

diff --git a/.github/workflows/devenv.yaml b/.github/workflows/devenv.yaml
--- a/.github/workflows/devenv.yaml
+++ b/.github/workflows/devenv.yaml
@@ -1,7 +1,8 @@
 ---
 name: Devenv
 
-on:
+# prettier-ignore
+on:  # yamllint disable-line rule:truthy
   push:
     branches:
       - trunk
@@ -11,9 +12,9 @@ on:
       - "trunk"
     paths:
       - .github/workflows/devenv.yaml
-      - devenv.lock
       - devenv.nix
       - devenv.yaml
+      - devenv.lock
       - devenv/**
 
 concurrency:
@@ -24,17 +25,16 @@ permissions:
   contents: write
   packages: write
   pull-requests: write
-  statuses: read
+  statuses: write
 
 env:
-  NIXPKGS_ALLOW_UNFREE: 1
-
-  REGISTRY: ghcr.io
-  ORGANISATION: ${{ github.repository_owner }}
-  PROJECT: ${{ github.event.repository.name }}
-
+  # GitHub
+  PROJECT: ${{ github.repository }}
   BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
   BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}
+
+  # Nix
+  NIXPKGS_ALLOW_UNFREE: 1
 
 defaults:
   run:
@@ -42,7 +42,7 @@ defaults:
 
 jobs:
   ##################################################
-  # Test
+  # Test the Development environment shell
   ##################################################
 
   test:
@@ -60,18 +60,6 @@ jobs:
           - ubuntu-latest
 
     steps:
-      - id: free_disk_space
-        name: Free Disk Space
-        uses: jlumbroso/free-disk-space@main
-        with:
-          tool-cache: true
-          android: true
-          dotnet: true
-          haskell: true
-          large-packages: true
-          docker-images: true
-          swap-storage: false
-
       - id: checkout_repository
         name: Checkout repository
         uses: actions/checkout@v4
@@ -89,6 +77,7 @@ jobs:
       - id: cachix
         name: "Enable Cachix ❄️"
         uses: cachix/cachix-action@v15
+        if: vars.CACHIX_CACHE_NAME != ''
         with:
           name: ${{ vars.CACHIX_CACHE_NAME }}
           authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
@@ -96,25 +85,44 @@ jobs:
           skipPush: false
 
       - id: cache
-        name: "Magic Nix cache ❄️"
+        name: Magic Nix cache
         uses: DeterminateSystems/magic-nix-cache-action@main
 
       - id: devenv_install
         name: Devenv install
         run: |
-          nix profile install nixpkgs#devenv
+          nix profile install --accept-flake-config nixpkgs#devenv
 
       - id: devenv_gc
         name: Devenv gc
         run: |
           devenv gc
 
-      - id: devenv_shell
-        name: Devenv shell
-        run: |
-          devenv shell
-
       - id: devenv_test
         name: Devenv test
         run: |
           devenv test
+
+      - id: devenv_status
+        name: Devenv (status)
+        if: always()
+        shell: devenv shell --quiet bash -- -e {0}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if [[ ${{ steps.devenv_test.outcome }} == 'success' ]];
+          then
+            RESULT="success"
+            DESCRIPTION="Devenv test passed"
+          else
+            RESULT="failure"
+            DESCRIPTION="Devenv test failed"
+          fi
+          gh api \
+            repos/${{ github.repository }}/statuses/${{ github.sha }} \
+            -f state=${RESULT} \
+            -f context="${{ github.workflow }}" \
+            -f description="${DESCRIPTION}" \
+            -f target_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" || {
+              echo "Failed to report devenv status"; exit 1;
+            }
